name: Hola github-Action #nombre del workflow
run-name: ¡Aprendiendo github action ! #nombre de la ejecucion del workflow
on: [push] #identificador del evento que activara el workflow
jobs:
  hola-mundo: # Nombre del job
    runs-on: ubuntu-latest #en que runner correra el job
    steps:
      - name: Paso1Checkout #nombre del paso 1
        uses: action/checkout@v3 #la accion a ejecutar
      - name: Definir variable #nombre paso 2
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script #nombre paso 3
        run: python S1-hola.py
