name: Hola_Variables-Secretos
run-name: Aprendiendo Variables-Secretos
on: 
  workflow_dispatch
env:
  dia_semana: 月曜日
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      saludo: hola
    steps:
      - name: Mandar_Saludo
        run: echo "$saludo, ${{ vars.NOMBRE }}. Hoy es ${{ env.dia_semana }}"
  saludo-secreto:
    runs-on: ubuntu-latest
    env:
      saludo: Hola 0_0
    steps:
      - name: saludo secreto
        run: echo "$saludo, ${{ vars.NOMBRE }}. Tu contraseña es: ${{ secrets.CONTRASENA }}"
