name: Triggers #Nombre del workflowa
run-name: Aprendiendo Triggers #Nombre que aparece en la seccion de actios
on:
  push: #primer trigger
    branches: #Indica sobre que ramas se quiere que se active el workflow con el push
      - master
  pull_request: #segundo trigger
    types: [opened, synchronize, reopened] #tipo de subacciones dentro de un pull request
    paths:
      - '**.py' #tipo de archivo o nombre queremos que se active
  issues: #tercer trigger
    types: # el tipo que se usara para que se ejecute el workflow
      - labeled
  workflow_dispatch: #cuarto trigger para ejecutra workflow de forma manual
    inputs:
      lenguaje_favorito: #nombre del primer input
        description: 'Lenguaje favorito'
        default: Python
        required: true #si es requerido
        type: choice #tipo opcion para elegir por el usuario
        options:
        - Python
        - JavaScript
        - Go
      nombre: #nombre del segundo input
        description: 'Tu nombre'
        required: true #si es requerido
        default: rvm2
        type: string
  schedule: #quinto triggers
    - cron: '15 22 * * *' #se ejecutara todos los dias 22:15 UTC
jobs:
  hola-mundo-manual: #nombre del 1 job
    runs-on: ubuntu-latest #serviosr donde corre el job
    steps:
      - name: Checkout #nombre del paso 1
        uses: actions/checkout@v3 #la accion a realizar
      - name: Definir nombre #nombre del paso 2
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV #comando a ejecutar
      - name: Definir lenguaje #nombre del paso 3
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
      - name: Correr script
        run: python S2-h_lenguaje.py
  hola-mundo: #nombre del 2 job
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python S1-hola.py
